### ISSUE TITLE
How to define a multi-readfile project in samplenames?

### ISSUE THREAD

**Issue by dgg32** [PacificBiosciences/pb-metagenomics-tools#1]
Hi. I am trying to use the Genome-Binning-Pipeline to process one of my pacbio metagenome project. After reading the Sample-Config-Example.yaml, the way I understand it, is that one read file and one contig file are the way to do it. But in my case, I have co-assembled three read files into one contig file, for example: three pacbio read files p1, p2 and p3 were assembled into assembly.contig.fasta.

So please, how should I proceed with the tool? Thank you.

**Comment by dportik** [comment]
Unless the reads all come from the same sample or population, we generally do not recommend performing co-assembly using HiFi reads.

If you choose to work with co-assembled data, your best strategy will be to merge all of your HiFi reads into a single fasta file. You will want coverage estimates that are based on all of the reads that were used for assembly, rather than just one set of reads. This should allow the binning step to work as intended. 

Please let me know if you have any other issues - documentation is in progress and will be available soon.
