### ISSUE TITLE
Error in DASinputSemiBin2 and DASinputMetabat2

### ISSUE THREAD

**Issue by MelodyMale** [PacificBiosciences/pb-metagenomics-tools#53]
I'm running this command in HiFi-MAG-Pipeline
`snakemake --snakefile Snakefile-hifimags.smk --configfile configs/Sample-Config.yaml -j 8 --use-conda`

and got some errors.

here are messages from both `DASinputSemiBin2.log` and `DASinputMetabat2.log`
`/bin/bash: Fasta_to_Scaffolds2Bin.sh: command not found`

**Comment by dportik** [comment]
Hello @MelodyMale ,
It seems that there is an issue with the `dastool.yml` environment, because the `Fasta_to_Scaffolds2Bin.sh` program is installed with DAS_Tool. 

A few users have mentioned issues with environments, and I recently updated the recipes (including for `dastool.yml`).

Could you try using the latest version of the environments and see if the error persists? You could replace all of them or copy/paste the new `dastool.yml` available into your `envs/` folder.

**Comment by MelodyMale** [comment]
@dportik Thank you for your response. I'm still getting the same error after changing `dastool.yml`

**Comment by nallsing-salk** [comment]
> @dportik Thank you for your response. I'm still getting the same error after changing `dastool.yml`

Hello, I am getting the same error as well, even with a clean installation of the pipeline.

**Comment by dportik** [comment]
Hi @MelodyMale and @nallsing-salk ,
It looks like the `Fasta_to_Scaffolds2Bin.sh` script was renamed to `Fasta_to_Contig2Bin.sh` in DAS_Tool v1.1.4, which is causing the issue.

As @nallsing-salk pointed out, pinning the version to 1.1.3 will allow it to run with the current snakemake file.

I will work on a fix to allow the most recent version of DAS_Tool to be used instead (which is preferable). I should have this early next week.

**Comment by nallsing-salk** [comment]
Awesome, thanks for the reply!
