### ISSUE TITLE
Error in rule DastoolAnalysis

### ISSUE THREAD

**Issue by MelodyMale** [PacificBiosciences/pb-metagenomics-tools#56]
I got an error from this command with Macbook Pro M1 chip
`snakemake --snakefile Snakefile-hifimags.smk --configfile configs/Sample-Config.yaml -j 8 --use-conda`

![messageImage_1682296384630](https://user-images.githubusercontent.com/31468410/233875992-f874b7de-3232-4b34-99a4-a9c697f70a2d.jpg)

Here are logs
```
DAS Tool 1.1.6 
Warning:  File is empty: /Users/wipoo/pb-metagenomic-tools/HiFi-MAG-Pipeline/4-DAStool/BO45.metabat2.tsv 
Analyzing assembly 
Predicting genes 
/Users/wipoo/pb-metagenomic-tools/HiFi-MAG-Pipeline/.snakemake/conda/622edad4b7a70377d8c28f54d270f512_/share/das_tool-1.1.6-0/src/prodigal_parallel.sh: line 8: shuf: command not found
split: 0: illegal line count
pullseq - failed to open names file /Users/wipoo/pb-metagenomic-tools/HiFi-MAG-Pipeline/4-DAStool/BO45/BO45_proteins.faa_DasToolParallel.tmp.*
Error:  Gene prediction failed.
```

**Comment by dportik** [comment]
Hi @MelodyMale,

It looks like metabat2 did not find any bins, because that input file for DAS_Tool is empty. However, DAS_Tool has been able to handle empty files since v1.1.3 (https://github.com/cmks/DAS_Tool/issues/67).

The error message indicates that `shuf` is not a known command. This is part of the `coreutils` package that is generally available on HPC environments but not standard on MAC (https://github.com/cmks/DAS_Tool/issues/9).

I would add `coreutils` to the `dastool.yml` environment recipe, and reinstall the environment:

```
name: dastool_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - das_tool == 1.1.6
  - coreutils
```

Try that and see if the error persists.

**Comment by MelodyMale** [comment]
@dportik Thank you for your help

Right now, I got a new error from Checkm2BinAnalysis instead.
Here are messages from `Checkm2BinAnalysis.log`

```
[04/25/2023 08:53:15 AM] INFO: Running CheckM2 version 1.0.1
[04/25/2023 08:53:15 AM] INFO: Custom database path provided for predict run. Checking database at /Users/wipoo/pb-metagenomic-tools/HiFi-MAG-Pipeline/CheckM2_database/uniref100.KO.1.dmnd...
[04/25/2023 08:53:25 AM] INFO: Running quality prediction workflow with 8 threads.
[04/25/2023 08:53:27 AM] INFO: Calling genes in 3 bins with 8 threads:

    Finished processing 1 of 3 (33.33%) bins.
    Finished processing 2 of 3 (66.67%) bins.
    Finished processing 3 of 3 (100.00%) bins.
[04/25/2023 08:53:33 AM] INFO: Calculating metadata for 3 bins with 8 threads:

    Finished processing 1 of 3 (33.33%) bin metadata.
    Finished processing 2 of 3 (66.67%) bin metadata.
    Finished processing 3 of 3 (100.00%) bin metadata.
[04/25/2023 08:53:34 AM] INFO: Annotating input genomes with DIAMOND using 8 threads
[04/25/2023 08:54:08 AM] INFO: Processing DIAMOND output
[04/25/2023 08:54:08 AM] ERROR: No DIAMOND annotation was generated. Exiting
```

**Comment by dportik** [comment]
Hi @MelodyMale,
This seems to be specific to your dataset, and I won't be able to reproduce this error.

It is possible there is something odd about the DIAMOND run. 
You can try using BLAST instead for this step by changing the option in the config file:
```
dastool:
  # The number of threads to use for DAS Tool.
  threads: 24

  # The engine for single copy gene searching, choices include:
  # blast, diamond, usearch.
  search: "diamond"                       <- change to "blast"
```

If the error persists, there may not be any relevant information detectable in the three long contigs identified. 

I'm not sure how this would happen, but it could be because they are not prokaryotic. 

If it is a human-derived sample, you may want to remove human contigs before running.

Beyond that, there is little I can do to solve the problem without access to the data.

**Comment by dportik** [comment]
Hi @MelodyMale,
This seems to be specific to your dataset, and I won't be able to reproduce this error.

It is possible there is something odd about the DIAMOND run, but I have not seen an error like this before. 

On possibility is there may not be any relevant information detectable in the three long contigs identified. I'm not sure how this would happen, but it could be because they are not prokaryotic.

If it is a human-derived sample, you may want to remove human contigs before running.

If you are stuck you can open an issue on the CheckM2 github page to see if there are other possible solutions:
https://github.com/chklovski/CheckM2/issues

**Comment by dportik** [comment]
Hi @MelodyMale,
This could also be a memory-related issue. 

See here:
https://github.com/chklovski/CheckM2/issues/58

In general, the HiFi-MAG-Pipeline is not something I would expect to run successfully on a laptop. It has substantial memory requirements for some steps, and even if you can get through CheckM2 it may fail elsewhere too.

**Comment by MelodyMale** [comment]
Hi @dportik,
Thank you for your help.

A memory-related issue sound makes sense. I only got 16GB, but HiFi-MAG-Pipeline requires at least 45GB.

Do you have any ways to limit memory?

**Comment by dportik** [comment]
Hi @MelodyMale,
Yes 16Gb is likely to be insufficient for several steps. 

The memory requirements unfortunately occur as a result of the designs for several external tools used in the workflow, which I do not develop or maintain.

I have tried to reduce memory when possible by allowing writing to a temporary directory (vs. holding in memory) for several steps across programs, but there are other steps which simply require high resources.
