### ISSUE TITLE
Taxonomic-Profiling-Diamond-Megan - Snakemake package conflicts cannot be resolved

### ISSUE THREAD

**Issue by psampara** [PacificBiosciences/pb-metagenomics-tools#65]
Hello,
I am trying to install the tools for the pipeline, "Taxonomic-Profiling-Diamond-Megan". I have miniconda3 running with version 23.7.2, and I am using Snakemake version 7.32.2. When I am trying to install the packages for this pipeline, either using Snakemake or manually, I am getting a package conflict which is not being resolved. The expected behavior was the installation of the tools in the "envs/general.yml" file

The command I used is: 
`snakemake  --snakefile Snakefile-diamoigfile configs/Sample-Config.yaml --use-conda --conda-create-envs-only --cores 2 --conda-frontend conda`

I used `--conda-frontend conda` because I am unable to install "mamba" on my cluster

The error I get and the packages in the conda environment are attached.

[conda_env_list.txt](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/12306193/conda_env_list.txt)
[pacbio_taxa_tool_error.txt](https://github.com/PacificBiosciences/pb-metagenomics-tools/files/12306194/pacbio_taxa_tool_error.txt)

**Comment by dportik** [comment]
Hi @psampara ,
Thanks for your patience. This should be fixed in the newest release ([v2.1.0](https://github.com/PacificBiosciences/pb-metagenomics-tools/releases/tag/v2.1.0)). 

The `general.yml` environment has been broken into several smaller environments that are specific to the particular rules.

 Please test this and let me know if your issue persists.

**Comment by dportik** [comment]
No updates from OP, closing issue for now.
