### ISSUE TITLE
NCBI-nt minimap2 Index too large

### ISSUE THREAD

**Issue by eparisis** [PacificBiosciences/pb-metagenomics-tools#71]
Name the workflow
Taxonomic-Profiling-Minimap-Megan

Describe the question and context
When creating the index file for the `minimap2` workflow, the resulting `.mmi` exceeds the expected size by a lot. 

In the documentation you mention that after indexing the `nt.gz` file from NCBIs FTP site, the resulting minimap2 index file should be about 850GB, but during the database creation I was monitoring the size of the resulting `.mmi` file and it was exceeding 2.2TB in size when I stopped it. The NCBI-nt database from: ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nt.gz* you suggest using is about 310GB large. The command I am using is `minimap2 -k 19 -w 10 -d mm2_nt_db.mmi nt.gz`

Am I missing something or do you have any suggestion on where to find good subsets of the `nt` database?

**Comment by dportik** [comment]
Hi @eparisis ,
I did not encounter that issue when creating the index, so can't comment on what may be happening here.

One possibility is to use RefSeq instead of the nt database, as it contains non-redundant sequences. 

If your goal is to obtain a taxonomic profile, I would recommend using the `Taxonomic-Profiling-sourmash` workflow instead. It is much faster, and performs better than the `Taxonomic-Profiling-Minimap-Megan` workflow in my benchmarks (for both precision & recall) .
